#####################################################################################
# CanBadger Window Specification                                                    #
# Copyright (c) 2020 Noelscher Consulting GmbH                                      #
#                                                                                   #
# Permission is hereby granted, free of charge, to any person obtaining a copy      #
# of this software and associated documentation files (the "Software"), to deal     #
# in the Software without restriction, including without limitation the rights      #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell         #
# copies of the Software, and to permit persons to whom the Software is             #
# furnished to do so, subject to the following conditions:                          #
#                                                                                   #
# The above copyright notice and this permission notice shall be included in        #
# all copies or substantial portions of the Software.                               #
#                                                                                   #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR        #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,          #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE       #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER            #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,     #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN         #
# THE SOFTWARE.                                                                     #
#####################################################################################

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Fri Mar 12 10:40:21 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.settingsTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.interfaceSelectionGrpBox = QtWidgets.QGroupBox(self.settingsTab)
        self.interfaceSelectionGrpBox.setObjectName("interfaceSelectionGrpBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.interfaceSelectionGrpBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.interfaceSelection = QtWidgets.QComboBox(self.interfaceSelectionGrpBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interfaceSelection.sizePolicy().hasHeightForWidth())
        self.interfaceSelection.setSizePolicy(sizePolicy)
        self.interfaceSelection.setObjectName("interfaceSelection")
        self.interfaceSelection.addItem("")
        self.horizontalLayout_4.addWidget(self.interfaceSelection)
        self.resetBtn = QtWidgets.QPushButton(self.interfaceSelectionGrpBox)
        self.resetBtn.setObjectName("resetBtn")
        self.horizontalLayout_4.addWidget(self.resetBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.interfaceSelectionGrpBox)
        self.canbadgerSettingsGrpBox = QtWidgets.QGroupBox(self.settingsTab)
        self.canbadgerSettingsGrpBox.setObjectName("canbadgerSettingsGrpBox")
        self.gridLayout = QtWidgets.QGridLayout(self.canbadgerSettingsGrpBox)
        self.gridLayout.setObjectName("gridLayout")
        self.canbadgerSettingLayout = QtWidgets.QGridLayout()
        self.canbadgerSettingLayout.setObjectName("canbadgerSettingLayout")
        self.nodeIdLineEdit = QtWidgets.QLineEdit(self.canbadgerSettingsGrpBox)
        self.nodeIdLineEdit.setObjectName("nodeIdLineEdit")
        self.canbadgerSettingLayout.addWidget(self.nodeIdLineEdit, 0, 1, 1, 1)
        self.nodeIdEditLabel = QtWidgets.QLabel(self.canbadgerSettingsGrpBox)
        self.nodeIdEditLabel.setObjectName("nodeIdEditLabel")
        self.canbadgerSettingLayout.addWidget(self.nodeIdEditLabel, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.canbadgerSettingLayout, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.canbadgerSettingsGrpBox)
        self.canSettingsGrpBox = QtWidgets.QGroupBox(self.settingsTab)
        self.canSettingsGrpBox.setObjectName("canSettingsGrpBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.canSettingsGrpBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CAN1SpeedSelection = QtWidgets.QComboBox(self.canSettingsGrpBox)
        self.CAN1SpeedSelection.setObjectName("CAN1SpeedSelection")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.setItemText(0, "")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.addItem("")
        self.CAN1SpeedSelection.addItem("")
        self.gridLayout_2.addWidget(self.CAN1SpeedSelection, 5, 0, 1, 1)
        self.CAN2SpeedSelection = QtWidgets.QComboBox(self.canSettingsGrpBox)
        self.CAN2SpeedSelection.setObjectName("CAN2SpeedSelection")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.setItemText(0, "")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.addItem("")
        self.CAN2SpeedSelection.addItem("")
        self.gridLayout_2.addWidget(self.CAN2SpeedSelection, 7, 0, 1, 1)
        self.enableBRIDGE1Checkbox = QtWidgets.QCheckBox(self.canSettingsGrpBox)
        self.enableBRIDGE1Checkbox.setObjectName("enableBRIDGE1Checkbox")
        self.gridLayout_2.addWidget(self.enableBRIDGE1Checkbox, 2, 0, 1, 1)
        self.enableCAN1Checkbox = QtWidgets.QCheckBox(self.canSettingsGrpBox)
        self.enableCAN1Checkbox.setObjectName("enableCAN1Checkbox")
        self.gridLayout_2.addWidget(self.enableCAN1Checkbox, 0, 0, 1, 1)
        self.enableCAN2Checkbox = QtWidgets.QCheckBox(self.canSettingsGrpBox)
        self.enableCAN2Checkbox.setObjectName("enableCAN2Checkbox")
        self.gridLayout_2.addWidget(self.enableCAN2Checkbox, 1, 0, 1, 1)
        self.CAN2SpeedLabel = QtWidgets.QLabel(self.canSettingsGrpBox)
        self.CAN2SpeedLabel.setObjectName("CAN2SpeedLabel")
        self.gridLayout_2.addWidget(self.CAN2SpeedLabel, 6, 0, 1, 1)
        self.enableBRIDGE2Checkbox = QtWidgets.QCheckBox(self.canSettingsGrpBox)
        self.enableBRIDGE2Checkbox.setObjectName("enableBRIDGE2Checkbox")
        self.gridLayout_2.addWidget(self.enableBRIDGE2Checkbox, 3, 0, 1, 1)
        self.CAN1SpeedLabel = QtWidgets.QLabel(self.canSettingsGrpBox)
        self.CAN1SpeedLabel.setObjectName("CAN1SpeedLabel")
        self.gridLayout_2.addWidget(self.CAN1SpeedLabel, 4, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.canSettingsGrpBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveNodeSettingsBtn = QtWidgets.QPushButton(self.settingsTab)
        self.saveNodeSettingsBtn.setObjectName("saveNodeSettingsBtn")
        self.horizontalLayout_3.addWidget(self.saveNodeSettingsBtn)
        self.eepromBtn = QtWidgets.QPushButton(self.settingsTab)
        self.eepromBtn.setObjectName("eepromBtn")
        self.horizontalLayout_3.addWidget(self.eepromBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.settingsTab, "")
        self.loggerTab = QtWidgets.QWidget()
        self.loggerTab.setObjectName("loggerTab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.loggerTab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.lineFilterLayout = QtWidgets.QGroupBox(self.loggerTab)
        self.lineFilterLayout.setObjectName("lineFilterLayout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.lineFilterLayout)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.filterFramesByIdLineEdit = QtWidgets.QLineEdit(self.lineFilterLayout)
        self.filterFramesByIdLineEdit.setText("")
        self.filterFramesByIdLineEdit.setObjectName("filterFramesByIdLineEdit")
        self.verticalLayout_13.addWidget(self.filterFramesByIdLineEdit)
        self.filterLayout.addWidget(self.lineFilterLayout)
        self.payloadFilterLayout = QtWidgets.QGroupBox(self.loggerTab)
        self.payloadFilterLayout.setObjectName("payloadFilterLayout")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.payloadFilterLayout)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.payloadFilterLineEdit = QtWidgets.QLineEdit(self.payloadFilterLayout)
        self.payloadFilterLineEdit.setObjectName("payloadFilterLineEdit")
        self.verticalLayout_14.addWidget(self.payloadFilterLineEdit)
        self.filterLayout.addWidget(self.payloadFilterLayout)
        self.miscFilterGrid = QtWidgets.QGridLayout()
        self.miscFilterGrid.setObjectName("miscFilterGrid")
        self.highlightCheckbox = QtWidgets.QCheckBox(self.loggerTab)
        self.highlightCheckbox.setObjectName("highlightCheckbox")
        self.miscFilterGrid.addWidget(self.highlightCheckbox, 0, 0, 1, 1)
        self.compactFilterCheckbox = QtWidgets.QCheckBox(self.loggerTab)
        self.compactFilterCheckbox.setObjectName("compactFilterCheckbox")
        self.miscFilterGrid.addWidget(self.compactFilterCheckbox, 0, 1, 1, 1)
        self.filterFramesByNewFramesAfterCheckbox = QtWidgets.QCheckBox(self.loggerTab)
        self.filterFramesByNewFramesAfterCheckbox.setObjectName("filterFramesByNewFramesAfterCheckbox")
        self.miscFilterGrid.addWidget(self.filterFramesByNewFramesAfterCheckbox, 1, 0, 1, 1)
        self.filterFramesAfterNSpinBox = QtWidgets.QSpinBox(self.loggerTab)
        self.filterFramesAfterNSpinBox.setMaximum(10000)
        self.filterFramesAfterNSpinBox.setObjectName("filterFramesAfterNSpinBox")
        self.miscFilterGrid.addWidget(self.filterFramesAfterNSpinBox, 1, 1, 1, 1)
        self.filterLayout.addLayout(self.miscFilterGrid)
        self.verticalLayout_12.addLayout(self.filterLayout)
        self.canLogView = CanLoggerTreeView(self.loggerTab)
        self.canLogView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.canLogView.setObjectName("canLogView")
        self.verticalLayout_12.addWidget(self.canLogView)
        self.logButtonsLayout = QtWidgets.QHBoxLayout()
        self.logButtonsLayout.setObjectName("logButtonsLayout")
        self.saveCanLogBtn = QtWidgets.QToolButton(self.loggerTab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveCanLogBtn.setIcon(icon)
        self.saveCanLogBtn.setObjectName("saveCanLogBtn")
        self.logButtonsLayout.addWidget(self.saveCanLogBtn)
        self.restoreCanLogBtn = QtWidgets.QToolButton(self.loggerTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/back-in-time.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreCanLogBtn.setIcon(icon1)
        self.restoreCanLogBtn.setObjectName("restoreCanLogBtn")
        self.logButtonsLayout.addWidget(self.restoreCanLogBtn)
        self.startCanLoggerBtn = QtWidgets.QPushButton(self.loggerTab)
        self.startCanLoggerBtn.setObjectName("startCanLoggerBtn")
        self.logButtonsLayout.addWidget(self.startCanLoggerBtn)
        self.verticalLayout_12.addLayout(self.logButtonsLayout)
        self.tabWidget.addTab(self.loggerTab, "")
        self.replayTab = QtWidgets.QWidget()
        self.replayTab.setObjectName("replayTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.replayTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.replayTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.replayMoveUpBtn = QtWidgets.QToolButton(self.groupBox_2)
        self.replayMoveUpBtn.setObjectName("replayMoveUpBtn")
        self.horizontalLayout_8.addWidget(self.replayMoveUpBtn)
        self.replayMoveDownBtn = QtWidgets.QToolButton(self.groupBox_2)
        self.replayMoveDownBtn.setObjectName("replayMoveDownBtn")
        self.horizontalLayout_8.addWidget(self.replayMoveDownBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.replayRemoveFrameBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.replayRemoveFrameBtn.setEnabled(False)
        self.replayRemoveFrameBtn.setObjectName("replayRemoveFrameBtn")
        self.horizontalLayout_8.addWidget(self.replayRemoveFrameBtn)
        self.addReplayFrameBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.addReplayFrameBtn.setEnabled(True)
        self.addReplayFrameBtn.setObjectName("addReplayFrameBtn")
        self.horizontalLayout_8.addWidget(self.addReplayFrameBtn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.replayFramesTableView = QtWidgets.QTableView(self.groupBox_2)
        self.replayFramesTableView.setObjectName("replayFramesTableView")
        self.verticalLayout_10.addWidget(self.replayFramesTableView)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.replayTab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.replayCountLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.replayCountLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replayCountLineEdit.sizePolicy().hasHeightForWidth())
        self.replayCountLineEdit.setSizePolicy(sizePolicy)
        self.replayCountLineEdit.setObjectName("replayCountLineEdit")
        self.horizontalLayout_2.addWidget(self.replayCountLineEdit)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        self.replayFrameIdLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.replayFrameIdLineEdit.setEnabled(False)
        self.replayFrameIdLineEdit.setObjectName("replayFrameIdLineEdit")
        self.horizontalLayout_2.addWidget(self.replayFrameIdLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.replayInterfaceSelection = QtWidgets.QComboBox(self.groupBox)
        self.replayInterfaceSelection.setObjectName("replayInterfaceSelection")
        self.replayInterfaceSelection.addItem("")
        self.replayInterfaceSelection.addItem("")
        self.horizontalLayout_2.addWidget(self.replayInterfaceSelection)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_11.addWidget(self.label_20)
        self.replayPayloadLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.replayPayloadLineEdit.setEnabled(False)
        self.replayPayloadLineEdit.setObjectName("replayPayloadLineEdit")
        self.verticalLayout_11.addWidget(self.replayPayloadLineEdit)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.startReplayBtn = QtWidgets.QPushButton(self.replayTab)
        self.startReplayBtn.setObjectName("startReplayBtn")
        self.verticalLayout_4.addWidget(self.startReplayBtn)
        self.tabWidget.addTab(self.replayTab, "")
        self.mitmTab = QtWidgets.QWidget()
        self.mitmTab.setObjectName("mitmTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mitmTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rulesGroupBox = QtWidgets.QGroupBox(self.mitmTab)
        self.rulesGroupBox.setObjectName("rulesGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.rulesGroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.MITMTopLayout = QtWidgets.QHBoxLayout()
        self.MITMTopLayout.setObjectName("MITMTopLayout")
        self.loadRulesFromFileBtn = QtWidgets.QToolButton(self.rulesGroupBox)
        self.loadRulesFromFileBtn.setText("")
        self.loadRulesFromFileBtn.setIcon(icon1)
        self.loadRulesFromFileBtn.setObjectName("loadRulesFromFileBtn")
        self.MITMTopLayout.addWidget(self.loadRulesFromFileBtn)
        self.saveRulesToFileBtn = QtWidgets.QToolButton(self.rulesGroupBox)
        self.saveRulesToFileBtn.setText("")
        self.saveRulesToFileBtn.setIcon(icon)
        self.saveRulesToFileBtn.setObjectName("saveRulesToFileBtn")
        self.MITMTopLayout.addWidget(self.saveRulesToFileBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.MITMTopLayout.addItem(spacerItem3)
        self.ruleNameLineEdit = QtWidgets.QLineEdit(self.rulesGroupBox)
        self.ruleNameLineEdit.setObjectName("ruleNameLineEdit")
        self.MITMTopLayout.addWidget(self.ruleNameLineEdit)
        self.saveRulesBtn = QtWidgets.QPushButton(self.rulesGroupBox)
        self.saveRulesBtn.setFlat(False)
        self.saveRulesBtn.setObjectName("saveRulesBtn")
        self.MITMTopLayout.addWidget(self.saveRulesBtn)
        self.MITMFileButton = QtWidgets.QPushButton(self.rulesGroupBox)
        self.MITMFileButton.setObjectName("MITMFileButton")
        self.MITMTopLayout.addWidget(self.MITMFileButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.MITMTopLayout.addItem(spacerItem4)
        self.removeRuleBtn = QtWidgets.QPushButton(self.rulesGroupBox)
        self.removeRuleBtn.setEnabled(False)
        self.removeRuleBtn.setObjectName("removeRuleBtn")
        self.MITMTopLayout.addWidget(self.removeRuleBtn)
        self.addRuleBtn = QtWidgets.QPushButton(self.rulesGroupBox)
        self.addRuleBtn.setObjectName("addRuleBtn")
        self.MITMTopLayout.addWidget(self.addRuleBtn)
        self.verticalLayout_6.addLayout(self.MITMTopLayout)
        self.rulesTableView = QtWidgets.QTableView(self.rulesGroupBox)
        self.rulesTableView.setObjectName("rulesTableView")
        self.verticalLayout_6.addWidget(self.rulesTableView)
        self.verticalLayout_7.addWidget(self.rulesGroupBox)
        self.ruleSettingsGroupBox = QtWidgets.QGroupBox(self.mitmTab)
        self.ruleSettingsGroupBox.setObjectName("ruleSettingsGroupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.ruleSettingsGroupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.conditionMessageIdLineEdit = QtWidgets.QLineEdit(self.ruleSettingsGroupBox)
        self.conditionMessageIdLineEdit.setEnabled(False)
        self.conditionMessageIdLineEdit.setMaxLength(4)
        self.conditionMessageIdLineEdit.setObjectName("conditionMessageIdLineEdit")
        self.gridLayout_9.addWidget(self.conditionMessageIdLineEdit, 2, 1, 1, 1)
        self.actionMaskLineEdit = QtWidgets.QLineEdit(self.ruleSettingsGroupBox)
        self.actionMaskLineEdit.setEnabled(False)
        self.actionMaskLineEdit.setText("")
        self.actionMaskLineEdit.setMaxLength(80)
        self.actionMaskLineEdit.setCursorPosition(0)
        self.actionMaskLineEdit.setObjectName("actionMaskLineEdit")
        self.gridLayout_9.addWidget(self.actionMaskLineEdit, 9, 1, 1, 1)
        self.argumentLabel = QtWidgets.QLabel(self.ruleSettingsGroupBox)
        self.argumentLabel.setObjectName("argumentLabel")
        self.gridLayout_9.addWidget(self.argumentLabel, 7, 0, 1, 1)
        self.ruleConditionLabel = QtWidgets.QLabel(self.ruleSettingsGroupBox)
        self.ruleConditionLabel.setObjectName("ruleConditionLabel")
        self.gridLayout_9.addWidget(self.ruleConditionLabel, 1, 0, 1, 1)
        self.actionArgumentLineEdit = QtWidgets.QLineEdit(self.ruleSettingsGroupBox)
        self.actionArgumentLineEdit.setEnabled(False)
        self.actionArgumentLineEdit.setObjectName("actionArgumentLineEdit")
        self.gridLayout_9.addWidget(self.actionArgumentLineEdit, 7, 1, 1, 1)
        self.ruleActionLabel = QtWidgets.QLabel(self.ruleSettingsGroupBox)
        self.ruleActionLabel.setObjectName("ruleActionLabel")
        self.gridLayout_9.addWidget(self.ruleActionLabel, 0, 0, 1, 1)
        self.ruleCondComboBox = QtWidgets.QComboBox(self.ruleSettingsGroupBox)
        self.ruleCondComboBox.setEnabled(False)
        self.ruleCondComboBox.setObjectName("ruleCondComboBox")
        self.gridLayout_9.addWidget(self.ruleCondComboBox, 1, 1, 1, 1)
        self.ruleTypeComboBox = QtWidgets.QComboBox(self.ruleSettingsGroupBox)
        self.ruleTypeComboBox.setEnabled(False)
        self.ruleTypeComboBox.setObjectName("ruleTypeComboBox")
        self.gridLayout_9.addWidget(self.ruleTypeComboBox, 0, 1, 1, 1)
        self.conditionMaskLineEdit = QtWidgets.QLineEdit(self.ruleSettingsGroupBox)
        self.conditionMaskLineEdit.setEnabled(False)
        self.conditionMaskLineEdit.setObjectName("conditionMaskLineEdit")
        self.gridLayout_9.addWidget(self.conditionMaskLineEdit, 4, 1, 1, 1)
        self.conditionMaskLabel = QtWidgets.QLabel(self.ruleSettingsGroupBox)
        self.conditionMaskLabel.setObjectName("conditionMaskLabel")
        self.gridLayout_9.addWidget(self.conditionMaskLabel, 4, 0, 1, 1)
        self.conditionTargetMessageIdLabel = QtWidgets.QLabel(self.ruleSettingsGroupBox)
        self.conditionTargetMessageIdLabel.setObjectName("conditionTargetMessageIdLabel")
        self.gridLayout_9.addWidget(self.conditionTargetMessageIdLabel, 2, 0, 1, 1)
        self.secondConditionValueLabel = QtWidgets.QLabel(self.ruleSettingsGroupBox)
        self.secondConditionValueLabel.setObjectName("secondConditionValueLabel")
        self.gridLayout_9.addWidget(self.secondConditionValueLabel, 9, 0, 1, 1)
        self.conditionValueLineEdit = QtWidgets.QLineEdit(self.ruleSettingsGroupBox)
        self.conditionValueLineEdit.setEnabled(False)
        self.conditionValueLineEdit.setObjectName("conditionValueLineEdit")
        self.gridLayout_9.addWidget(self.conditionValueLineEdit, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.ruleSettingsGroupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 3, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.ruleSettingsGroupBox)
        self.startMITMButton = QtWidgets.QPushButton(self.mitmTab)
        self.startMITMButton.setObjectName("startMITMButton")
        self.verticalLayout_7.addWidget(self.startMITMButton)
        self.tabWidget.addTab(self.mitmTab, "")
        self.sdCardTab = QtWidgets.QWidget()
        self.sdCardTab.setObjectName("sdCardTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.sdCardTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.deleteFileBtn = QtWidgets.QPushButton(self.sdCardTab)
        self.deleteFileBtn.setObjectName("deleteFileBtn")
        self.horizontalLayout_10.addWidget(self.deleteFileBtn)
        self.downloadFileBtn = QtWidgets.QPushButton(self.sdCardTab)
        self.downloadFileBtn.setObjectName("downloadFileBtn")
        self.horizontalLayout_10.addWidget(self.downloadFileBtn)
        self.uploadFileBtn = QtWidgets.QPushButton(self.sdCardTab)
        self.uploadFileBtn.setObjectName("uploadFileBtn")
        self.horizontalLayout_10.addWidget(self.uploadFileBtn)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 5, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.sdCardTab)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.sdCardFolderLineEdit = QtWidgets.QLineEdit(self.sdCardTab)
        self.sdCardFolderLineEdit.setObjectName("sdCardFolderLineEdit")
        self.horizontalLayout_9.addWidget(self.sdCardFolderLineEdit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.refreshSdCardBtn = QtWidgets.QPushButton(self.sdCardTab)
        self.refreshSdCardBtn.setObjectName("refreshSdCardBtn")
        self.horizontalLayout_9.addWidget(self.refreshSdCardBtn)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.sdCardTreeView = SDTreeView(self.sdCardTab)
        self.sdCardTreeView.setObjectName("sdCardTreeView")
        self.gridLayout_8.addWidget(self.sdCardTreeView, 1, 0, 1, 1)
        self.tabWidget.addTab(self.sdCardTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_config = QtWidgets.QAction(MainWindow)
        self.actionLoad_config.setObjectName("actionLoad_config")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.deleteFileBtn, self.downloadFileBtn)
        MainWindow.setTabOrder(self.downloadFileBtn, self.sdCardFolderLineEdit)
        MainWindow.setTabOrder(self.sdCardFolderLineEdit, self.refreshSdCardBtn)
        MainWindow.setTabOrder(self.refreshSdCardBtn, self.sdCardTreeView)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "CanBadger Server", None, -1))
        self.interfaceSelectionGrpBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Select Interface", None, -1))
        self.interfaceSelection.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "None", None, -1))
        self.resetBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Reset CB", None, -1))
        self.canbadgerSettingsGrpBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "CanBadger Settings", None, -1))
        self.nodeIdEditLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Node ID:", None, -1))
        self.canSettingsGrpBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "CAN Settings", None, -1))
        self.CAN1SpeedSelection.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "20000", None, -1))
        self.CAN1SpeedSelection.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "33333", None, -1))
        self.CAN1SpeedSelection.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "40000", None, -1))
        self.CAN1SpeedSelection.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "50000", None, -1))
        self.CAN1SpeedSelection.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "62500", None, -1))
        self.CAN1SpeedSelection.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "83333", None, -1))
        self.CAN1SpeedSelection.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "100000", None, -1))
        self.CAN1SpeedSelection.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "125000", None, -1))
        self.CAN1SpeedSelection.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "250000", None, -1))
        self.CAN1SpeedSelection.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "500000", None, -1))
        self.CAN1SpeedSelection.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "750000", None, -1))
        self.CAN1SpeedSelection.setItemText(12, QtWidgets.QApplication.translate("MainWindow", "800000", None, -1))
        self.CAN1SpeedSelection.setItemText(13, QtWidgets.QApplication.translate("MainWindow", "1000000", None, -1))
        self.CAN2SpeedSelection.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "20000", None, -1))
        self.CAN2SpeedSelection.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "33333", None, -1))
        self.CAN2SpeedSelection.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "40000", None, -1))
        self.CAN2SpeedSelection.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "50000", None, -1))
        self.CAN2SpeedSelection.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "62500", None, -1))
        self.CAN2SpeedSelection.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "83333", None, -1))
        self.CAN2SpeedSelection.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "100000", None, -1))
        self.CAN2SpeedSelection.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "125000", None, -1))
        self.CAN2SpeedSelection.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "250000", None, -1))
        self.CAN2SpeedSelection.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "500000", None, -1))
        self.CAN2SpeedSelection.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "750000", None, -1))
        self.CAN2SpeedSelection.setItemText(12, QtWidgets.QApplication.translate("MainWindow", "800000", None, -1))
        self.CAN2SpeedSelection.setItemText(13, QtWidgets.QApplication.translate("MainWindow", "1000000", None, -1))
        self.enableBRIDGE1Checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "Bridge CAN1", None, -1))
        self.enableCAN1Checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "Logging CAN1", None, -1))
        self.enableCAN2Checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "Logging CAN2", None, -1))
        self.CAN2SpeedLabel.setText(QtWidgets.QApplication.translate("MainWindow", "CAN2 Speed:", None, -1))
        self.enableBRIDGE2Checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "Bridge CAN2", None, -1))
        self.CAN1SpeedLabel.setText(QtWidgets.QApplication.translate("MainWindow", "CAN1 Speed:", None, -1))
        self.saveNodeSettingsBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.eepromBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Store in EEPROM", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), QtWidgets.QApplication.translate("MainWindow", "Interface Settings", None, -1))
        self.lineFilterLayout.setTitle(QtWidgets.QApplication.translate("MainWindow", "Filter by ID", None, -1))
        self.filterFramesByIdLineEdit.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Filter by frame id.</p><p>You can enter multiple IDs, separated by comma.</p><p><br/></p><p>Example: 0080,0081</p></body></html>", None, -1))
        self.payloadFilterLayout.setTitle(QtWidgets.QApplication.translate("MainWindow", "Filter by Payload", None, -1))
        self.payloadFilterLineEdit.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Filter frame payloads to match your input:</span></p><p><span style=\" font-size:10pt;\">- bytes seperated by whitespaces (0a B7 cC)</span></p><p><span style=\" font-size:10pt;\">- _ is a wildcard byte</span></p><p><span style=\" font-size:10pt;\">- * is 0..n wildcard bytes</span></p><p><span style=\" font-size:10pt;\">Example input: _ f5 * AC<br/>matches all payloads with 2nd byte F5 and ending on AC. </span></p></body></html>", None, -1))
        self.highlightCheckbox.setText(QtWidgets.QApplication.translate("MainWindow", "Highlight Changes", None, -1))
        self.compactFilterCheckbox.setText(QtWidgets.QApplication.translate("MainWindow", "Compact View", None, -1))
        self.filterFramesByNewFramesAfterCheckbox.setText(QtWidgets.QApplication.translate("MainWindow", "only show new IDs after", None, -1))
        self.filterFramesAfterNSpinBox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Show only frames from new IDs that are recorded after $value frames</p></body></html>", None, -1))
        self.saveCanLogBtn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Save logged frames to a JSON file</p></body></html>", None, -1))
        self.saveCanLogBtn.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.restoreCanLogBtn.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.startCanLoggerBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Not Connected", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.loggerTab), QtWidgets.QApplication.translate("MainWindow", "Logger", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Frame Sequence", None, -1))
        self.replayMoveUpBtn.setText(QtWidgets.QApplication.translate("MainWindow", "↑", None, -1))
        self.replayMoveDownBtn.setText(QtWidgets.QApplication.translate("MainWindow", "↓", None, -1))
        self.replayRemoveFrameBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Remove", None, -1))
        self.addReplayFrameBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Add", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Modify Frame", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Count", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "ID", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Interface", None, -1))
        self.replayInterfaceSelection.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.replayInterfaceSelection.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Payload (HEX)", None, -1))
        self.startReplayBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Start Replay", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.replayTab), QtWidgets.QApplication.translate("MainWindow", "Replay", None, -1))
        self.rulesGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Rules", None, -1))
        self.loadRulesFromFileBtn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Load rules from a valid txt file</p></body></html>", None, -1))
        self.saveRulesToFileBtn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Save rules to a txt file</p></body></html>", None, -1))
        self.ruleNameLineEdit.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Enter filename the rules will be stored under on the canbadger.</p><p>File has to be a .txt, max. 16 chars.</p></body></html>", None, -1))
        self.ruleNameLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Desired Filename (e.g. rules.txt)", None, -1))
        self.saveRulesBtn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Save Rules on the canbadger SD</p></body></html>", None, -1))
        self.saveRulesBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Upload Rules", None, -1))
        self.MITMFileButton.setText(QtWidgets.QApplication.translate("MainWindow", "MITM from File", None, -1))
        self.removeRuleBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Remove", None, -1))
        self.addRuleBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Add", None, -1))
        self.ruleSettingsGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Rule Settings", None, -1))
        self.conditionMessageIdLineEdit.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>The frame id will always be matched against this value</p></body></html>", None, -1))
        self.actionMaskLineEdit.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Bytemask for the rule actions that require specific bytes:</p><p>A 1 will match a byte and a 0 will ignore the byte. (Leftmost ist MSB)</p></body></html>", None, -1))
        self.argumentLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Action Argument:", None, -1))
        self.ruleConditionLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Condition:", None, -1))
        self.ruleActionLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Action:", None, -1))
        self.ruleCondComboBox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Condition:</p><p>Frames are first matched by ID and then, it will try to match the condition specified here.</p></body></html>", None, -1))
        self.conditionMaskLineEdit.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Bytemask for the rule condition:</p><p>A 1 will match a byte and a 0 will ignore the byte. (Leftmost ist MSB)</p></body></html>", None, -1))
        self.conditionMaskLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Condition Mask:", None, -1))
        self.conditionTargetMessageIdLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Target Frame ID:", None, -1))
        self.secondConditionValueLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Action Mask", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Condition Value:", None, -1))
        self.startMITMButton.setText(QtWidgets.QApplication.translate("MainWindow", "Start MITM", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mitmTab), QtWidgets.QApplication.translate("MainWindow", "MITM", None, -1))
        self.deleteFileBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Delete File", None, -1))
        self.downloadFileBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Download File", None, -1))
        self.uploadFileBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Upload File", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "Folder:", None, -1))
        self.sdCardFolderLineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "/", None, -1))
        self.refreshSdCardBtn.setText(QtWidgets.QApplication.translate("MainWindow", "Refresh", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sdCardTab), QtWidgets.QApplication.translate("MainWindow", "Manage SD Card", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionLoad_config.setText(QtWidgets.QApplication.translate("MainWindow", "Load config", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))

from views import CanLoggerTreeView, SDTreeView
